// Default permissions for each role — mirrors client/src/config/permissions.ts
const ALL_PERMISSION_IDS = [
  "dashboard.view",
  "pos.create",
  "pos.view",
  "pos.refund",
  "pos.discount",
  "inventory.view",
  "inventory.add",
  "inventory.edit",
  "inventory.delete",
  "categories.manage",
  "reports.view",
  "reports.export",
  "users.view",
  "users.add",
  "users.edit",
  "users.delete",
  "users.permissions",
  "settings.view",
  "settings.edit",
  "returns.create",
  "returns.view",
];

const DEFAULT_ROLE_PERMISSIONS = {
  admin: Object.fromEntries(ALL_PERMISSION_IDS.map((id) => [id, true])),

  cashier: {
    "dashboard.view": true,
    "pos.create": true,
    "pos.view": true,
    "pos.refund": false,
    "pos.discount": true,
    "inventory.view": true,
    "inventory.add": false,
    "inventory.edit": false,
    "inventory.delete": false,
    "categories.manage": false,
    "reports.view": true,
    "reports.export": false,
    "users.view": false,
    "users.add": false,
    "users.edit": false,
    "users.delete": false,
    "users.permissions": false,
    "settings.view": true,
    "settings.edit": false,
    "returns.create": true,
    "returns.view": true,
  },

  staff: {
    "dashboard.view": true,
    "pos.create": true,
    "pos.view": true,
    "pos.refund": false,
    "pos.discount": false,
    "inventory.view": true,
    "inventory.add": false,
    "inventory.edit": false,
    "inventory.delete": false,
    "categories.manage": false,
    "reports.view": false,
    "reports.export": false,
    "users.view": false,
    "users.add": false,
    "users.edit": false,
    "users.delete": false,
    "users.permissions": false,
    "settings.view": false,
    "settings.edit": false,
    "returns.create": false,
    "returns.view": false,
  },
};

module.exports = { DEFAULT_ROLE_PERMISSIONS, ALL_PERMISSION_IDS };
