// Default permissions for each role — mirrors client/src/config/permissions.ts
const ALL_PERMISSION_IDS = [
  "dashboard.view",
  "pos.create",
  "pos.view",
  "pos.refund",
  "pos.discount",
  "pos.price_override",
  "inventory.view",
  "inventory.add",
  "inventory.edit",
  "inventory.delete",
  "categories.manage",
  "reports.view",
  "reports.export",
  "users.view",
  "users.add",
  "users.edit",
  "users.delete",
  "users.permissions",
  "settings.view",
  "settings.edit",
  "returns.create",
  "returns.view",
  "customers.view",
  "customers.history",
  "accounts.view",
  "accounts.ledger",
  "accounts.manage",
  "payments.view",
  "payments.create",
  "payments.cancel",
  "purchases.view",
  "purchases.create",
  "purchases.cancel",
  "period.close",
  "period.reopen",
];

const DEFAULT_ROLE_PERMISSIONS = {
  admin: Object.fromEntries(ALL_PERMISSION_IDS.map((id) => [id, true])),

  // Cashier: POS / retail flow only. No accounting.
  cashier: {
    "dashboard.view": true,
    "pos.create": true,
    "pos.view": true,
    "pos.refund": false,
    "pos.discount": true,
    "pos.price_override": false,
    "inventory.view": true,
    "inventory.add": false,
    "inventory.edit": false,
    "inventory.delete": false,
    "categories.manage": false,
    "reports.view": true,
    "reports.export": false,
    "users.view": false,
    "users.add": false,
    "users.edit": false,
    "users.delete": false,
    "users.permissions": false,
    "settings.view": true,
    "settings.edit": false,
    "returns.create": true,
    "returns.view": true,
    "customers.view": true,
    "customers.history": true,
    "accounts.view": false,
    "accounts.ledger": false,
    "accounts.manage": false,
    "payments.view": false,
    "payments.create": false,
    "payments.cancel": false,
    "purchases.view": false,
    "purchases.create": false,
    "purchases.cancel": false,
    "period.close": false,
    "period.reopen": false,
  },

  // Staff: minimal — POS + inventory read.
  staff: {
    "dashboard.view": true,
    "pos.create": true,
    "pos.view": true,
    "pos.refund": false,
    "pos.discount": false,
    "pos.price_override": false,
    "inventory.view": true,
    "inventory.add": false,
    "inventory.edit": false,
    "inventory.delete": false,
    "categories.manage": false,
    "reports.view": false,
    "reports.export": false,
    "users.view": false,
    "users.add": false,
    "users.edit": false,
    "users.delete": false,
    "users.permissions": false,
    "settings.view": false,
    "settings.edit": false,
    "returns.create": false,
    "returns.view": false,
    "customers.view": false,
    "customers.history": false,
    "accounts.view": false,
    "accounts.ledger": false,
    "accounts.manage": false,
    "payments.view": false,
    "payments.create": false,
    "payments.cancel": false,
    "purchases.view": false,
    "purchases.create": false,
    "purchases.cancel": false,
    "period.close": false,
    "period.reopen": false,
  },

  // Accountant: accounting / wholesale flow only. No POS, no retail.
  accountant: {
    "dashboard.view": false,
    "pos.create": false,
    "pos.view": false,
    "pos.refund": false,
    "pos.discount": false,
    "pos.price_override": false,
    "inventory.view": false,
    "inventory.add": false,
    "inventory.edit": false,
    "inventory.delete": false,
    "categories.manage": false,
    "reports.view": false,
    "reports.export": false,
    "users.view": false,
    "users.add": false,
    "users.edit": false,
    "users.delete": false,
    "users.permissions": false,
    "settings.view": false,
    "settings.edit": false,
    "returns.create": false,
    "returns.view": false,
    "customers.view": false,
    "customers.history": false,
    "accounts.view": true,
    "accounts.ledger": true,
    "accounts.manage": true,
    "payments.view": true,
    "payments.create": true,
    "payments.cancel": true,
    "purchases.view": true,
    "purchases.create": true,
    "purchases.cancel": true,
    "period.close": true,
    "period.reopen": true,
  },
};

module.exports = { DEFAULT_ROLE_PERMISSIONS, ALL_PERMISSION_IDS };
